name: 'SWM: Deploy to Azure'

on:
  push:
    branches:
    - main

jobs:
  build-test:
    name: 'Build and Test'

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      shell: bash
      run: |
        ehco "FUNCTION_APP_PATH=${{ github.workspace }}/api" >> $GITHUB_ENV

    - name: Check environment vairavles
      shell: bash
      run: |
        echo $FUNCTION_APP_PATH